
domain: localhost

image:
  registry: ghcr.io
  repository: andrejpetras/todo-core
  tag: ${quarkus.application.version}

service:
  port: 80

pod:
  port: 8080

livenessProbe:
  url: /q/health/live
readinessProbe:
  url: /q/health/ready

config:
  health:
    liveness: true
    readiness: true