name: build
on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_PAT }}
      - name: Set up java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
      - name: Project version
        id: project_version
        uses: lorislab/samo-action@v1.0.0
        with:
          args: samo project version
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build project
        run: mvn -ntp -B -e clean package -Dquarkus.container-image.registry=${{ env.REGISTRY }} -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.application.version=${{ steps.project_version.outputs.stdout }}